load("//src/starkware/cairo/lang:cairo_rules.bzl", "cairo_library")

package(default_visibility = ["//visibility:public"])

cairo_library(
    name = "segment_arena_cairo_lib",
    srcs = [
        "segment_arena.cairo",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/starkware/cairo/common:cairo_common_cairo_lib",
    ],
)
